### ISSUE TITLE
sendMail results with BadRequest

### ISSUE THREAD

**Issue by stomicic** [OfficeDev/O365-Angular-Unified-API-Connect#3]
Each sendMail call results with following error:   message: "Unsupported segment type."
Azure AD is configured properly.

**Comment by martellaj** [comment]
Thanks, @stomicic. I'll look into this today.

**Comment by stomicic** [comment]
Hi @martellaj ,
what do you think, is this the error in sample or is this an API error?
Can you help me fix the issue?

**Comment by martellaj** [comment]
It's an API issue. Keep in mind that the unified API is currently in preview, so things can (and will) change now and then. I know the issue and will have a fix published tonight. I'll ping you when it's in master.

**Comment by martellaj** [comment]
Fixed. :+1:

**Comment by stomicic** [comment]
Thanks a lot!

**Comment by surikoya** [comment]
I am getting the same error(Unsupported segment type) again. I downloaded the code for nodejs and got his error. Is there some patch for the client code to fix this?

**Comment by martellaj** [comment]
Thanks, @surikoya. Looks like our Node sample had not been updated yet. I just patched it, so please pull the latest and try it again. In the future, please log issues in the repo you have issues with. Helps us keep organized. Thanks! :+1:

**Comment by philipodonnell** [comment]
FYI, just downloaded the node sample and this error still occurs.

**Comment by martellaj** [comment]
@philipodonnell Please open an issue on that repo. Thanks! :rocket:
